---
# Run ansible-playbook stop.yml --extra-vars='{"vm": "vm"}'
# vm        : is the name of your vm in inventory

- name: Stop running virtualbox vm
  hosts: localhost
  tasks:
  - include_vars:
      # include vars of your vm
      file: "{{ inventory_dir }}/host_vars/{{ vm }}"
      name: testible

  # Shutdown the vm for tests use acpipowerbutton because poweroff loose files
  - name: Shutdown the vm
    command: "VBoxManage controlvm {{ testible.host.vbox.uuid }} acpipowerbutton"

